### ISSUE TITLE
まだMisskeyが残ってる

### ISSUE THREAD

**Issue by mattyatea** [Type4ny-Project/Type4ny#25]
ウィジェットのサーバー情報
ロード画面
など

https://mattyaski.co/notes/9y5b0wxuc6

**Comment by mattyatea** [comment]
「詳しく」のリンクがMisskey（https://misskey-hub.net/docs/about-misskey/）のまま

**Comment by mattyatea** [comment]
I ❤ #Misskey

**Comment by Suzulu-activity** [comment]
別のissue建てるほどでもないからここに書いちゃうけど、たぶんここにもType4ny足したほうがいい
![image](https://github.com/user-attachments/assets/a89022d5-01c9-4b17-ba15-ff5839cfdff4)

**Comment by mattyatea** [comment]
たしかに

**Comment by JunDarapapa** [comment]
○実績まわり
- just setting up my tp4ny
→　tp4ny表記はアリでしょうか？　こだわりなければ「Type4ny」表記はどうでしょうか

- I love Misskey 投稿すると実績獲得の通知がくる
※しかし実績一覧には表示されず、通知をみると空欄で表示されている

- ビギナーⅠ、ミスキストⅠ、等
→　実績の解説「今日からね僕は ミスキストってことで」や実績名称の「ミスキスト」表現を変えたい

○サーバー情報（/about）
- フィードバックが https://github.com/misskey-dev/misskey/issues/new へのリンクのまま
→　正しくは https://github.com/Type4ny-Project/Type4ny/issues/new

※　コントロールパネル→全般→リポジトリURLを https://github.com/Type4ny-Project/Type4ny と変更しても反映されない

○サーバーホーム（非ログイン時のホーム画面）
- ドキュメントが https://misskey-hub.net/ja/docs/for-users/ へのリンクのまま

※　Sharkeyも同じくMisskeyユーザー向けガイドへのリンクのままになっている
※　Firefish/Iceshrimp/Catodonは「ドキュメント」項目がない

→　リンクごとなくしてもいいかもしれませんね

○ゲーム
- Misskey Games
→　リンクテキストのMisskeyを取りたい（バブルゲームやリバーシのイラストはそのまま）

※　Sharkeyはもっと！の中のメニューはGames表記、ゲーム選択画面はMisskey Games表記

**Comment by mattyatea** [comment]
ありがとうございます！！🙏🙏🙏

**Comment by JunDarapapa** [comment]
Vup後クライアント起動時に初回表示する「Type4nyが更新されました！」の「更新情報を見る」のリンク先がMisskeyのまま
https://github.com/Type4ny-Project/Type4ny/blob/8b32d5ab832250656880eb6b89e5d276201448c2/packages/frontend/src/components/MkUpdated.vue#L30

※Sharkeyはリンク先が以下の通りです
`https://activitypub.software/TransFem-org/Sharkey/-/releases/${version}`
※Fanboxの記事のURLは任意に指定できないみたいですね

**Comment by mattyatea** [comment]
一旦 ミスキスト などの名称の変更はどういう風に変更するか考える。
それ以外の問題は下記のコミットで多分解決したのでIssue Close
https://github.com/Type4ny-Project/Type4ny/commit/ccc3bbd796a8526319dae90bbb09b59403e576a3
