### ISSUE TITLE
なんとかかんとかはオリジナルのType4nyを改変したバージョンを使用しています。 って表示される

### ISSUE THREAD

**Issue by mattyatea** [Type4ny-Project/Type4ny#26]
#25 と近い
https://mattyaski.co/notes/9y5b0wxuc6

**Comment by mattyatea** [comment]
https://github.com/Type4ny-Project/Type4ny/commit/ccc3bbd796a8526319dae90bbb09b59403e576a3
このコミットで修正

**Comment by JunDarapapa** [comment]
closeしているのでここにぶら下げていいのか分かりませんが、
クライアント起動時「（サーバー名）について」ポップアップが表示されてしまいます
「Type4nyについて」は `/about-type4ny` へのリンク 
![スクリーンショット 2024-09-17 000502](https://github.com/user-attachments/assets/5dbfc73d-49e6-48ea-b86a-f9773cbe8b0d)

ソース改変はしていない設定になっています
![スクリーンショット 2024-09-17 001354](https://github.com/user-attachments/assets/94b5787b-b1d6-4f23-8217-0c0329fb698c)

今回の修正分でこちらも対応済でしたら申し訳ないのですが、念のため追記します
