### ISSUE TITLE
enhance:同一ノートreaction上限をロールポリシーで管理する

### ISSUE THREAD

**Issue by Suzulu-activity** [Type4ny-Project/Type4ny#27]
ロールでユーザー毎に同一ノートに対するreaction送信可能回数を変えられるようにする。
信頼できるユーザーは多く振り分けたり、
逆に0にしたら0にしたで制限ロールにも使えるかなって。

**Comment by mattyatea** [comment]
制限ロールは別で設けたいかも

**Comment by mattyatea** [comment]
制限ロール別個にしてくれたら自分が作った実装を流用できるし🥴

**Comment by mattyatea** [comment]
一旦Configでだけ制御できるようにして後々考えればいい感じになった
https://github.com/Type4ny-Project/Type4ny/commit/5b3b2992d09db2da0c9685291af292befee9158d
