### ISSUE TITLE
（ログインボーナス機能）ポイント名が変更できない、ポイントの修正もしたい、等

### ISSUE THREAD

**Issue by JunDarapapa** [Type4ny-Project/Type4ny#42]
### 💡 Summary

（ログインボーナス機能）ポイント名が変更できない、ポイントの修正もしたい、等

### 🥰 Expected Behavior

- コントロールパネル > ブランディングページでポイント名を変更・保存したら反映される
![スクリーンショット 2024-09-17 003602](https://github.com/user-attachments/assets/fe0e15b3-06bd-4ee8-a780-2df95925aded)

- ポイントのデフォルト名が「ポイント」「point」で表記ゆれしているので統一したい

- ポイント付与を誤った時（やペナルティ）など、ポイントの変更（回収？剥奪？）もしたい

- そもそも、ひとり鯖など、ログインボーナス機能が必要ではない場合の非表示化についても今後検討してほしい
　- プロフィール概要での表示可否
　- 通知する／しないの可否
　- 付与する／しないの可否

### 🤬 Actual Behavior

- 保存してもポイント名の変更内容が反映されない（再度ブランディングページを開くと空欄のまま）
- デフォルトポイント名が、ユーザープロフィール画面では「ポイント」、通知欄では「～pointゲットしました！」と表記ゆれがある
- 付与しかできない（気を付けて付与すればいいだけとは思いますが）

### 📝 Steps to Reproduce

省略

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:https://darapapa.misskey.one/
* Misskey:Type4ny 0.1.3-beta
```

### 🛰 Backend Environment (for server admin)

```markdown
下記省略
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by JunDarapapa** [comment]
回収はマイナスのポイント付与でできるという知見を得ました
![Screenshot_2024-09-17-02-13-10-280_com android chrome-edit](https://github.com/user-attachments/assets/6f78eb83-a5fa-4473-820c-4e23028ebd8a)

**Comment by mattyatea** [comment]
- [ ] ポイント名を編集できるようにする
- [ ] ポイントの剥奪のUIをわかりやすくする
- [ ] 表記揺れを治す
- [ ] ログボ機能のオンオフをできるようにする
- [ ] ログボ機能でログボの通知をオフにできるようにする
- [ ] ポイントをプロフィールに表示するか選べるようにする
- [ ] ユーザーに対して付与するかロールで選択できるようにする
