### ISSUE TITLE
Fix: 死んでいるゴリラ化機能の進退

### ISSUE THREAD

**Issue by Suzulu-activity** [Type4ny-Project/Type4ny#48]
関連コードを削除するか、UIから削除するか、はたまた蘇生させるか。

**Comment by mattyatea** [comment]
関連コード削除でいいと感じた

**Comment by mattyatea** [comment]
https://github.com/Type4ny-Project/Type4ny/commit/5d53e6cc00e51f12c360943485f6c90c9c0b4b00
