### ISSUE TITLE
Enhance: apple-touch-icon.png をType4nyのブランドロゴにしたい

### ISSUE THREAD

**Issue by JunDarapapa** [Type4ny-Project/Type4ny#52]
### Summary

https://github.com/Type4ny-Project/Type4ny/blob/develop/packages/backend/assets/apple-touch-icon.png
apple-touch-icon.png がMisskeyロゴのまま。このため、darapapa.misskey.one のようにサーバーアイコンを指定していないサーバーでPWAを作成するとMisskeyロゴがアイコンとなってしまう。

![1000040037](https://github.com/user-attachments/assets/9cf95e97-5a86-4cb0-af08-b8536f3abb26)

※仕様は下記の通りのようです
https://github.com/misskey-dev/misskey/issues/6589

### Purpose

よろしくお願いします。いつもありがとうございます。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by mattyatea** [comment]
✅
