### ISSUE TITLE
bug:オリジナル画像を保持のスイッチが表示されない

### ISSUE THREAD

**Issue by Suzulu-activity** [Type4ny-Project/Type4ny#61]
![image](https://github.com/user-attachments/assets/b22db2ca-4c8e-431e-bc8d-f81365addf2f)
prismisskeyと9ineverse.com βで再現を確認

本来あるべき姿
![image](https://github.com/user-attachments/assets/9abff56b-a039-4aeb-a402-f87ce1b8f063)

**Comment by JunDarapapa** [comment]
TLのオプションも、ON/OFFスイッチが見えなくなってしまいました
「センシティブなファイルを含むノートを表示」は途中でテキストが省略されています

項目を選択すると、表示非表示は切り替わります
![202409242259](https://github.com/user-attachments/assets/94a6fee9-9d86-4f4b-bbac-ad408c1de955)

darapapa.misskey.one、PrisMisskey、まっちゃすきー。で確認しています（Type4ny 1.0.0）

**Comment by Suzulu-activity** [comment]
![image](https://github.com/user-attachments/assets/c5473ab2-0ad9-4426-bf67-59d153ba5984)
popupMenuのスイッチが死んでそう

**Comment by Suzulu-activity** [comment]
![image](https://github.com/user-attachments/assets/5af0d606-db63-41e6-9968-ccbb5b3c5e86)
MkSwitchButton.vueが消えてただけだった。
マージミスかな。
