### ISSUE TITLE
サーバーホーム画面のユーザー数・ノート数が見れない、ライトモードで実績の通知アイコンが見えない

### ISSUE THREAD

**Issue by JunDarapapa** [Type4ny-Project/Type4ny#64]
○サーバーホーム画面のユーザー数・ノート数が見れない
サーバーホーム画面（未ログイン状態）で、ユーザー数・ノート数を見ようと画面の一番下へスクロールすると、連合先情報と重なり見ることができない（スクロールバーを微妙に動かすと見られなくはないが…）
ユーザー数・ノート数の項目の下に、適切な空欄の領域が必要

・PC（Windows11）、chromeにて確認
・PrisMisskeyで確認
（※dev.9ineverseは連合していないので連合先情報が表示されず、一見問題ないように見えます）

※画面キャプチャ下記参照
https://darapapa.misskey.one/notes/9yfz57b0vh
　

○ライトモードだと実績の通知アイコンが見えない
実績の通知欄に表示されるアイコンの背景が透過設定になっている？
ダークモードでは問題なく見えるが、ライトモードの場合、★も背景も白くなるため、アイコンが表示されていないように見えてしまう
※ログインボーナスはMisskeyと同じく背景が黄色なのでどちらのモードでも見え方は変わりません

※画面キャプチャ下記参照
https://darapapa.misskey.one/notes/9ygs2a5r3w

**Comment by mattyatea** [comment]
１つめは解決済み✅
２つ目も解決✅
